var wms_layers = [];

var lyr_quito2019style_0 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "http://www.geoportaligm.gob.ec/orto/wms",
    attributions: ' ',
                              params: {
                                "LAYERS": "quito%202019",
                                "TILED": "true",
                                "VERSION": "1.3.0"},
                            })),
                            title: "quito 2019 style",
                            opacity: 1.000000,
                            
                            
                          });
              wms_layers.push([lyr_quito2019style_0, 1]);
var format_LIMITE_PARROQUIAL_COD_CNE_1 = new ol.format.GeoJSON();
var features_LIMITE_PARROQUIAL_COD_CNE_1 = format_LIMITE_PARROQUIAL_COD_CNE_1.readFeatures(json_LIMITE_PARROQUIAL_COD_CNE_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_LIMITE_PARROQUIAL_COD_CNE_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_LIMITE_PARROQUIAL_COD_CNE_1.addFeatures(features_LIMITE_PARROQUIAL_COD_CNE_1);
var lyr_LIMITE_PARROQUIAL_COD_CNE_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_LIMITE_PARROQUIAL_COD_CNE_1, 
                style: style_LIMITE_PARROQUIAL_COD_CNE_1,
                popuplayertitle: "LIMITE_PARROQUIAL_COD_CNE",
                interactive: true,
    title: 'LIMITE_PARROQUIAL_COD_CNE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_0.png" /> 10 DE AGOSTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1.png" /> 10 NOVIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_2.png" /> 11 DE NOVIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_3.png" /> 12 DE DICIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_4.png" /> 12 DE MARZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_5.png" /> 16 DE AGOSTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_6.png" /> 18 DE OCTUBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_7.png" /> 24 DE MAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_8.png" /> 27 DE ABRIL /LA NARANJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_9.png" /> 27 DE SEPTIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_10.png" /> 28 DE MAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_11.png" /> 4 DE DICIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_12.png" /> 5 DE AGOSTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_13.png" /> 5 DE JUNIO/HUIMBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_14.png" /> 6 DE JULIO DE CUELLAJE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_15.png" /> 9 DE MAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_16.png" /> 9 DE OCTUBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_17.png" /> A.BAQUERIZO M /JUJAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_18.png" /> ABANIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_19.png" /> ABDON CALDERON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_20.png" /> ABDON CALDERON / LA UNION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_21.png" /> ABRAHAM CALAZACON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_22.png" /> ACHUPALLAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_23.png" /> AGUAS NEGRAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_24.png" /> AHUANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_25.png" /> ALAMOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_26.png" /> ALANGASI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_27.png" /> ALAQUEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_28.png" /> ALAUSI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_29.png" /> ALEJANDRO LABAKA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_30.png" /> ALHAJUELA /BAJO GRANDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_31.png" /> ALLURIQUIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_32.png" /> ALOAG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_33.png" /> ALOASI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_34.png" /> ALSHI /9 DE OCTUBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_35.png" /> ALTO TAMBO/GUADAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_36.png" /> AMAGUAÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_37.png" /> AMALUZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_38.png" /> AMARILLOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_39.png" /> AMAZONAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_40.png" /> AMBATILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_41.png" /> AMBUQUI/CHOTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_42.png" /> AMERICA /LA CERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_43.png" /> ANCHAYACU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_44.png" /> ANCON/PALMA REAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_45.png" /> ANCONCITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_46.png" /> ANDRADE MARIN/LOURDES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_47.png" /> ANDRES DE VERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_48.png" /> ANGAMARCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_49.png" /> ANGEL PEDRO GILER<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_50.png" /> ANGEL POLIVIO CHAVEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_51.png" /> ANGOCHAGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_52.png" /> ANIBAL SAN ANDRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_53.png" /> ANTONIO J. HOLGUIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_54.png" /> ANTONIO SOTOMAYOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_55.png" /> APUELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_56.png" /> ARAJUNO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_57.png" /> ARAPICOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_58.png" /> ARCAPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_59.png" /> ARCHIDONA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_60.png" /> ARENILLAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_61.png" /> ARQ.SIXTO DURAN BALLEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_62.png" /> ASCAZUBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_63.png" /> ASUNCION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_64.png" /> ATACAMES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_65.png" /> ATAHUALPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_66.png" /> ATAHUALPA /CHIPZALATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_67.png" /> ATAHUALPA /HABASPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_68.png" /> ATAHUALPA/CAMARONES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_69.png" /> ATOCHA FICOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_70.png" /> ATUNTAQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_71.png" /> AUGUSTO N MARTINEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_72.png" /> AURELIO BAYAS MARTINEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_73.png" /> AVILA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_74.png" /> AYACUCHO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_75.png" /> AYAPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_76.png" /> AZOGUES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_77.png" /> BABA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_78.png" /> BACHILLERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_79.png" /> BAEZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_80.png" /> BAHIA DE CARAQUEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_81.png" /> BALAO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_82.png" /> BALLENITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_83.png" /> BALNEARIO JAMBELI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_84.png" /> BALSAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_85.png" /> BALZAPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_86.png" /> BALZAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_87.png" /> BAÑOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_88.png" /> BAQUERIZO MORENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_89.png" /> BARBONES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_90.png" /> BARRAGANETE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_91.png" /> BARREIRO /SANTA RITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_92.png" /> BARTOLOME RUIZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_93.png" /> BELISARIO QUEVEDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_94.png" /> BELLA VISTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_95.png" /> BELLAMARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_96.png" /> BELLAVISTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_97.png" /> BENITEZ /PACHANLICA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_98.png" /> BERMEJOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_99.png" /> BIBLIAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_100.png" /> BILBAO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_101.png" /> BILOVAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_102.png" /> BOCANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_103.png" /> BOLASPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_104.png" /> BOLIVAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_105.png" /> BOLIVAR/SAGRARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_106.png" /> BOMBOIZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_107.png" /> BOMBOLI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_108.png" /> BORBON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_109.png" /> BORRERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_110.png" /> BOYACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_111.png" /> BUENAVISTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_112.png" /> BULAN / J. VICTOR IZQUIERDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_113.png" /> CACHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_114.png" /> CAHUASQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_115.png" /> CAJABAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_116.png" /> CALACALI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_117.png" /> CALCETA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_118.png" /> CALDERON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_119.png" /> CALPI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_120.png" /> CALUMA / SAN ANTONIO/<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_121.png" /> CAMARONES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_122.png" /> CAMILO PONCE ENRIQUEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_123.png" /> CAMPOZANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_124.png" /> CAÑAQUEMADA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_125.png" /> CAÑAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_126.png" /> CAÑARIBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_127.png" /> CANCHAGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_128.png" /> CANDILEJOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_129.png" /> CANELOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_130.png" /> CANGAHUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_131.png" /> CANGONAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_132.png" /> CANI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_133.png" /> CANOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_134.png" /> CANUTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_135.png" /> CAP. AUGUSTO RIVADENEIRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_136.png" /> CAPIRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_137.png" /> CAPZOL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_138.png" /> CARACOL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_139.png" /> CARANQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_140.png" /> CARBO/CONCEPCION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_141.png" /> CARCABON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_142.png" /> CARCELEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_143.png" /> CARIAMANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_144.png" /> CARLOS ESPINOZA LARREA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_145.png" /> CARLOS J. AROSEMENA TOLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_146.png" /> CAROLINA /GUALLUPI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_147.png" /> CARONDELET<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_148.png" /> CASACAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_149.png" /> CASANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_150.png" /> CASCOL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_151.png" /> CATACOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_152.png" /> CATAMAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_153.png" /> CATARAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_154.png" /> CAYAMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_155.png" /> CAZADEROS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_156.png" /> CEBADAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_157.png" /> CELIANO MONGE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_158.png" /> CELICA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_159.png" /> CENTRO HISTORICO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_160.png" /> CEVALLOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_161.png" /> CHACARITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_162.png" /> CHACRAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_163.png" /> CHAGUARPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_164.png" /> CHAMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_165.png" /> CHANDUY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_166.png" /> CHANGAIMINA /LA LIBERTAD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_167.png" /> CHANTACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_168.png" /> CHANTILIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_169.png" /> CHAQUINAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_170.png" /> CHARAPOTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_171.png" /> CHAUCHA / ANGAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_172.png" /> CHAUPI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_173.png" /> CHAVEZPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_174.png" /> CHECA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_175.png" /> CHECA JIDCAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_176.png" /> CHIBUNGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_177.png" /> CHICAN / GUILLERMO ORTEGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_178.png" /> CHICANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_179.png" /> CHIGUAZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_180.png" /> CHIGUILPE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_181.png" /> CHIGUINDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_182.png" /> CHILE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_183.png" /> CHILIBULO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_184.png" /> CHILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_185.png" /> CHILLANES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_186.png" /> CHILLOGALLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_187.png" /> CHIMBACALLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_188.png" /> CHINCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_189.png" /> CHIQUICHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_190.png" /> CHIQUINTAD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_191.png" /> CHIRIJOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_192.png" /> CHITAN DE NAVARRETES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_193.png" /> CHITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_194.png" /> CHOBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_195.png" /> CHONE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_196.png" /> CHONTADURO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_197.png" /> CHONTAMARCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_198.png" /> CHONTAPUNTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_199.png" /> CHORDELEG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_200.png" /> CHOROCOPTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_201.png" /> CHUGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_202.png" /> CHUGCHILAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_203.png" /> CHUMBLIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_204.png" /> CHUMUNDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_205.png" /> CHUNCHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_206.png" /> CHUPIANZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_207.png" /> CHUQUIRIBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_208.png" /> CHURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_209.png" /> CIANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_210.png" /> CIUDAD NUEVA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_211.png" /> CLEMENTE BAQUERIZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_212.png" /> COCHAPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_213.png" /> COCHAPATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_214.png" /> COJIMIES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_215.png" /> COJITAMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_216.png" /> COLAIZACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_217.png" /> COLIMES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_218.png" /> COLON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_219.png" /> COLON ELOY DE MARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_220.png" /> COLONCHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_221.png" /> COLORADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_222.png" /> COLUMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_223.png" /> COMITE DEL PUEBLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_224.png" /> COMPUD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_225.png" /> CONCEPCION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_226.png" /> CONOCOTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_227.png" /> CONONACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_228.png" /> CONSTANTINO FERNANDEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_229.png" /> CONVENTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_230.png" /> COPAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_231.png" /> CORDONCILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_232.png" /> CORNEJO ASTORGA /TANDAPI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_233.png" /> COSANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_234.png" /> COTALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_235.png" /> COTOCOLLAO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_236.png" /> COTOGCHOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_237.png" /> COTUNDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_238.png" /> CRISTOBAL COLON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_239.png" /> CRNEL. LORENZO GARAICOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_240.png" /> CRNL MARCELINO MARIDUENAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_241.png" /> CRNL.CARLOS CONCHA TORRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_242.png" /> CRUCITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_243.png" /> CRUZPAMBA/BUSTAMANTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_244.png" /> CUBE / CHANCAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_245.png" /> CUBIJIES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_246.png" /> CUCHAENTZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_247.png" /> CUMANDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_248.png" /> CUMBARATZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_249.png" /> CUMBAYA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_250.png" /> CUMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_251.png" /> CUNCHIBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_252.png" /> CURARAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_253.png" /> CURTINCAPAC<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_254.png" /> CUSUBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_255.png" /> CUTCHIL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_256.png" /> CUTUGLAGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_257.png" /> CUYABENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_258.png" /> CUYUJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_259.png" /> DANIEL CORDOVA TORAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_260.png" /> DAULE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_261.png" /> DAYUMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_262.png" /> DELEG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_263.png" /> DIVINO NINO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_264.png" /> DR MIGUEL EGAS/PEGUCHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_265.png" /> DR. CAMILO PONCE E.<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_266.png" /> DR. MIGUEL MORAN LUCIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_267.png" /> DUCUR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_268.png" /> DUG-DUG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_269.png" /> DURENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_270.png" /> ECHEANDIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_271.png" /> ECUADOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_272.png" /> EL AIRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_273.png" /> EL ALTAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_274.png" /> EL ANEGADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_275.png" /> EL ANGEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_276.png" /> EL ARENAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_277.png" /> EL BATAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_278.png" /> EL CABO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_279.png" /> EL CAMBIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_280.png" /> EL CARMELO/EL PUN/<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_281.png" /> EL CARMEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_282.png" /> EL CARMEN DE PIJILI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_283.png" /> EL CARMEN DE PUTUMAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_284.png" /> EL CHACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_285.png" /> EL CHICAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_286.png" /> EL CHORRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_287.png" /> EL CISNE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_288.png" /> EL CONDADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_289.png" /> EL CORAZON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_290.png" /> EL DORADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_291.png" /> EL DORADO DE CASCALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_292.png" /> EL EDEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_293.png" /> EL ENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_294.png" /> EL ESFUERZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_295.png" /> EL GOALTAL / LAS JUNTAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_296.png" /> EL GUABO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_297.png" /> EL GUISMI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_298.png" /> EL IDEAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_299.png" /> EL INGENIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_300.png" /> EL LAUREL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_301.png" /> EL LIMO /MARIANA DE JESUS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_302.png" /> EL LIMON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_303.png" /> EL LUCERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_304.png" /> EL PAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_305.png" /> EL PANGUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_306.png" /> EL PARAISO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_307.png" /> EL PARAISO DE CELEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_308.png" /> EL PIEDRERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_309.png" /> EL PLAYON DE SN. FRANCISCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_310.png" /> EL PORVENIR DEL CARMEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_311.png" /> EL PROGRESO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_312.png" /> EL RECREO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_313.png" /> EL RETIRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_314.png" /> EL REVENTADOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_315.png" /> EL ROSARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_316.png" /> EL ROSARIO /RUMICHACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_317.png" /> EL SAGRARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_318.png" /> EL SALTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_319.png" /> EL TABLON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_320.png" /> EL TAMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_321.png" /> EL TRIUNFO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_322.png" /> EL VECINO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_323.png" /> ELOY ALFARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_324.png" /> ELOY ALFARO / SAN FELIPE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_325.png" /> ELOY ALFARO /DURAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_326.png" /> EMILIO MARIA TERAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_327.png" /> ENOKANQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_328.png" /> ESMERALDAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_329.png" /> EUGENIO ESPEJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_330.png" /> FACUNDO VELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_331.png" /> FATIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_332.png" /> FEBRES CORDERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_333.png" /> FERNANDEZ SALVADOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_334.png" /> FLAVIO ALFARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_335.png" /> FLORES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_336.png" /> FRANCISCO PACHECO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_337.png" /> FUNDOCHAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_338.png" /> GABRIEL I VEINTIMILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_339.png" /> GALERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_340.png" /> GARCIA MORENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_341.png" /> GARCIA MORENO / LLURIMAGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_342.png" /> GARZAREAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_343.png" /> GENERAL ELOY ALFARO DELGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_344.png" /> GENERAL FARFAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_345.png" /> GIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_346.png" /> GIRON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_347.png" /> GONZALEZ SUAREZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_348.png" /> GONZALO DIAZ DE PINEDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_349.png" /> GONZALO PIZARRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_350.png" /> GONZANAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_351.png" /> GONZOL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_352.png" /> GRAL. A. E. GALLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_353.png" /> GRAL. LEONIDAS PLAZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_354.png" /> GRAL. PROAÑO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_355.png" /> GRAL. VERNAZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_356.png" /> GRAL.ELIZALDE /BUCAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_357.png" /> GRAL.ELOY ALFARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_358.png" /> GRAL.MORALES / SOCARTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_359.png" /> GRAL.PEDRO MONTERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_360.png" /> GRAL.VILLAMIL / PLAYAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_361.png" /> GUACHANAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_362.png" /> GUACHAPALA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_363.png" /> GUADALUPE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_364.png" /> GUALACEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_365.png" /> GUALAQUIZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_366.png" /> GUALE/STO.DOMINGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_367.png" /> GUALEA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_368.png" /> GUALEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_369.png" /> GUALLETURO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_370.png" /> GUAMANI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_371.png" /> GUAMOTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_372.png" /> GUANANDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_373.png" /> GUANAZAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_374.png" /> GUANGAJE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_375.png" /> GUANGOPOLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_376.png" /> GUANUJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_377.png" /> GUAPAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_378.png" /> GUARAINAC<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_379.png" /> GUARE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_380.png" /> GUASAGANDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_381.png" /> GUASUNTOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_382.png" /> GUAYACAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_383.png" /> GUAYAQUIL DE ALPACHACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_384.png" /> GUAYAS / PUERTO NUEVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_385.png" /> GUAYLLABAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_386.png" /> GUAYQUICHUMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_387.png" /> GUAYTACAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_388.png" /> GUAYZIMI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_389.png" /> GUEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_390.png" /> GUIZHAGUIÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_391.png" /> HATUN SUMAKU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_392.png" /> HERMANO MIGUEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_393.png" /> HONORATO VASQUEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_394.png" /> HUACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_395.png" /> HUACHI CHICO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_396.png" /> HUACHI GRANDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_397.png" /> HUACHI LORETO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_398.png" /> HUALTACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_399.png" /> HUAMBALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_400.png" /> HUAMBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_401.png" /> HUAMBOYA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_402.png" /> HUAQUILLAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_403.png" /> HUASAGA /WAMPUIK<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_404.png" /> HUAYNACAPAC<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_405.png" /> HUERTAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_406.png" /> HUIGRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_407.png" /> IGNACIO FLORES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_408.png" /> ILAPO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_409.png" /> IMANTAG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_410.png" /> IMBAYA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_411.png" /> IÑAQUITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_412.png" /> INDANZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_413.png" /> INES ARANGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_414.png" /> INGAPIRCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_415.png" /> ISIDRO AYORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_416.png" /> ISINLIVI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_417.png" /> ISLA DE BEJUCAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_418.png" /> ISLA SANTA MARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_419.png" /> ITCHIMBIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_420.png" /> IZAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_421.png" /> JADAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_422.png" /> JAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_423.png" /> JAMBELI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_424.png" /> JARAMIJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_425.png" /> JAVIER LOYOLA / CHUQUIPATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_426.png" /> JERUSALEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_427.png" /> JESUS MARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_428.png" /> JIJON Y CAAMAÑO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_429.png" /> JIMBILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_430.png" /> JIMBURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_431.png" /> JIPIJAPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_432.png" /> JORDAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_433.png" /> JOSE LUIS TAMAYO / MUEY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_434.png" /> JOSEGUANGO BAJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_435.png" /> JUAN BAUTISTA AGUIRRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_436.png" /> JUAN BENIGNO VELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_437.png" /> JUAN DE VELASCO / PONGOR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_438.png" /> JUAN GOMEZ RENDON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_439.png" /> JUAN MONTALVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_440.png" /> JUBONES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_441.png" /> JULCUY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_442.png" /> JULIO ANDRADE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_443.png" /> JULIO E MORENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_444.png" /> JUMON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_445.png" /> JUNCAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_446.png" /> JUNIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_447.png" /> JUNQUILLAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_448.png" /> KENNEDY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_449.png" /> LA ARGELIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_450.png" /> LA AURORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_451.png" /> LA AVANZADA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_452.png" /> LA BELLEZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_453.png" /> LA BOCANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_454.png" /> LA BONITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_455.png" /> LA CANDELARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_456.png" /> LA CANELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_457.png" /> LA CHONTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_458.png" /> LA CONCEPCION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_459.png" /> LA CONCORDIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_460.png" /> LA DOLOROSA DEL PRIORATO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_461.png" /> LA ECUATORIANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_462.png" /> LA ESMERALDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_463.png" /> LA ESPERANZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_464.png" /> LA FERROVIARIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_465.png" /> LA IBERIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_466.png" /> LA JOYA DE LOS SACHAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_467.png" /> LA LIBERTAD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_468.png" /> LA MAGDALENA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_469.png" /> LA MANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_470.png" /> LA MATRIZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_471.png" /> LA MENA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_472.png" /> LA MERCED<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_473.png" /> LA MERCED DE BUENOS AIRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_474.png" /> LA PAZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_475.png" /> LA PEAÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_476.png" /> LA PENINSULA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_477.png" /> LA PILA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_478.png" /> LA PROVIDENCIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_479.png" /> LA RAMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_480.png" /> LA SOFIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_481.png" /> LA SUSAYA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_482.png" /> LA TINGUE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_483.png" /> LA TOLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_484.png" /> LA TRONCAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_485.png" /> LA UNION<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_486.png" /> LA VICTORIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_487.png" /> LA VICTORIA DE IMBANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_488.png" /> LA VICTORIA/LAS LAJAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_489.png" /> LA VILLEGAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_490.png" /> LAGARTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_491.png" /> LAGO SAN PEDRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_492.png" /> LAS GOLONDRINAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_493.png" /> LAS LOJAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_494.png" /> LAS MERCEDES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_495.png" /> LAS NAVES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_496.png" /> LAS PAMPAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_497.png" /> LASCANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_498.png" /> LAURO GUERRERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_499.png" /> LEONIDAS PLAZA G.<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_500.png" /> LEONIDAS PROAÑO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_501.png" /> LETAMENDI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_502.png" /> LICAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_503.png" /> LICTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_504.png" /> LIMONAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_505.png" /> LIMONCOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_506.png" /> LIMONES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_507.png" /> LINARES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_508.png" /> LITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_509.png" /> LIZARZABURU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_510.png" /> LLACAO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_511.png" /> LLAGOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_512.png" /> LLANO CHICO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_513.png" /> LLIGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_514.png" /> LLOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_515.png" /> LLUZHAPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_516.png" /> LODANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_517.png" /> LOGROÑO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_518.png" /> LOMA DE FRANCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_519.png" /> LOMAS DE SARGENTILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_520.png" /> LORETO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_521.png" /> LOS ANDES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_522.png" /> LOS ANGELES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_523.png" /> LOS ENCUENTROS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_524.png" /> LOS ESTEROS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_525.png" /> LOURDES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_526.png" /> LUDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_527.png" /> LUIS CORDERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_528.png" /> LUIS CORDERO VEGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_529.png" /> LUIS GALARZA O. (DELEGSOL)<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_530.png" /> LUIS TELLO / LAS PALMAS /<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_531.png" /> LUIS VARGAS TORRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_532.png" /> LUMBAQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_533.png" /> LUZ DE AMERICA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_534.png" /> MACARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_535.png" /> MACAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_536.png" /> MACHACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_537.png" /> MACHALA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_538.png" /> MACHALILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_539.png" /> MACHANGARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_540.png" /> MACUMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_541.png" /> MADRE TIERRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_542.png" /> MAGDALENA/CHAPACOTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_543.png" /> MAGRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_544.png" /> MAJUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_545.png" /> MALACATOS/VALLADOLID<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_546.png" /> MALCHINGUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_547.png" /> MALDONADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_548.png" /> MALIMPIA / GUAYLLABAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_549.png" /> MALVAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_550.png" /> MANGA DEL CURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_551.png" /> MANGAHURCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_552.png" /> MANGLARALTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_553.png" /> MANTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_554.png" /> MANU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_555.png" /> MANUEL INOCENCIO PARRALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_556.png" /> MANUEL J. CALLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_557.png" /> MARCABELI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_558.png" /> MARCOS ESPINEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_559.png" /> MARIANO ACOSTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_560.png" /> MARIANO MORENO/CALLASAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_561.png" /> MARISCAL SUCRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_562.png" /> MARISCAL SUCRE/HUAQUES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_563.png" /> MATAJE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_564.png" /> MATUS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_565.png" /> MEMBRILLAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_566.png" /> MEMBRILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_567.png" /> MENDEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_568.png" /> MERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_569.png" /> MERCADILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_570.png" /> MERCEDES MOLINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_571.png" /> MILAGRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_572.png" /> MILAGROS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_573.png" /> MILTON REYES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_574.png" /> MINDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_575.png" /> MIRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_576.png" /> MOCACHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_577.png" /> MOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_578.png" /> MOLLETURO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_579.png" /> MONAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_580.png" /> MONTALVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_581.png" /> MONTALVO / HORQUETA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_582.png" /> MONTALVO /SABANETA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_583.png" /> MONTALVO/ANDOAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_584.png" /> MONTECRISTI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_585.png" /> MONTEOLIVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_586.png" /> MONTERREY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_587.png" /> MORALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_588.png" /> MORASPUNGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_589.png" /> MOROMORO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_590.png" /> MORRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_591.png" /> MUISNE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_592.png" /> MULALILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_593.png" /> MULALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_594.png" /> MULLIQUINDIL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_595.png" /> MULTI /  NULTI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_596.png" /> MULTITUD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_597.png" /> MULUNCAY GRANDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_598.png" /> NABON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_599.png" /> NAMBACOLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_600.png" /> NANEGAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_601.png" /> NANEGALITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_602.png" /> NARANJAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_603.png" /> NARANJITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_604.png" /> NARCISA DE JESUS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_605.png" /> NAYON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_606.png" /> NAZON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_607.png" /> NICOLAS INFANTE DIAZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_608.png" /> NIEVES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_609.png" /> NOBOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_610.png" /> NONO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_611.png" /> NOVILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_612.png" /> NUEVA FATIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_613.png" /> NUEVA LOJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_614.png" /> NUEVA TARQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_615.png" /> NUEVO PARAISO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_616.png" /> NUEVO QUITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_617.png" /> NUEVO ROCAFUERTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_618.png" /> NUEVO SANTA ROSA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_619.png" /> OCHOA LEON/MATRIZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_620.png" /> OCTAVIO CORDERO PALACIOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_621.png" /> OLMEDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_622.png" /> OLMEDO /PUCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_623.png" /> OLMEDO/PESILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_624.png" /> OLMEDO/SAN ALEJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_625.png" /> OÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_626.png" /> ORIANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_627.png" /> OTON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_628.png" /> OYACACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_629.png" /> PABLO ARENAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_630.png" /> PABLO SEXTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_631.png" /> PACAYACU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_632.png" /> PACCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_633.png" /> PACHICUTZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_634.png" /> PACTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_635.png" /> PAJAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_636.png" /> PALANDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_637.png" /> PALENQUE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_638.png" /> PALESTINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_639.png" /> PALETILLAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_640.png" /> PALLATANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_641.png" /> PALMA ROJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_642.png" /> PALMALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_643.png" /> PALMAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_644.png" /> PALMIRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_645.png" /> PALO QUEMADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_646.png" /> PALORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_647.png" /> PAMPANAL DE BOLIVAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_648.png" /> PAN DE AZUCAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_649.png" /> PANACOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_650.png" /> PANCHO NEGRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_651.png" /> PANGUINTZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_652.png" /> PANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_653.png" /> PANZALEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_654.png" /> PAPALLACTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_655.png" /> PAQUISHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_656.png" /> PARAISO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_657.png" /> PASA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_658.png" /> PASAJE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_659.png" /> PASCUALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_660.png" /> PATAQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_661.png" /> PATATE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_662.png" /> PATRICIA PILAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_663.png" /> PATUCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_664.png" /> PAUTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_665.png" /> PEDERNALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_666.png" /> PEDRO CARBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_667.png" /> PEDRO PABLO GOMEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_668.png" /> PEDRO VICENTE MALDONADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_669.png" /> PELILEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_670.png" /> PELILEO GRANDE /R. MINO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_671.png" /> PEÑAHERRERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_672.png" /> PENIPE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_673.png" /> PERUCHO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_674.png" /> PIARTAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_675.png" /> PICAYHUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_676.png" /> PICHINCHA /GERMUD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_677.png" /> PICOAZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_678.png" /> PIEDRAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_679.png" /> PIFO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_680.png" /> PILAHUIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_681.png" /> PILALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_682.png" /> PILLARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_683.png" /> PIMAMPIRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_684.png" /> PIMOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_685.png" /> PIÑAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_686.png" /> PIÑAS GRANDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_687.png" /> PINDAL /FEDERICO PAEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_688.png" /> PINDILIG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_689.png" /> PINGUILI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_690.png" /> PINLLOPATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_691.png" /> PINTAG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_692.png" /> PIOTER<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_693.png" /> PISHILATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_694.png" /> PISTISHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_695.png" /> PLAN PILOTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_696.png" /> PLATANILLOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_697.png" /> PLAZA GUTIERREZ/CALVARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_698.png" /> POALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_699.png" /> POMASQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_700.png" /> POMONA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_701.png" /> POMPEYA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_702.png" /> PONCEANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_703.png" /> PORTOVELO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_704.png" /> PORTOVIEJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_705.png" /> POSORJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_706.png" /> PRESIDENTE URBINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_707.png" /> PRINCIPAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_708.png" /> PROGRESO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_709.png" /> PTO. BAQUERIZO MORENO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_710.png" /> PTO. FCO. DE ORELLANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_711.png" /> PUCAPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_712.png" /> PUCARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_713.png" /> PUCAYACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_714.png" /> PUEBLO NUEVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_715.png" /> PUEBLO VIEJO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_716.png" /> PUELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_717.png" /> PUELLARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_718.png" /> PUEMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_719.png" /> PUENGASI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_720.png" /> PUERTO AYORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_721.png" /> PUERTO BOLIVAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_722.png" /> PUERTO CAYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_723.png" /> PUERTO JELI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_724.png" /> PUERTO LIBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_725.png" /> PUERTO LIMON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_726.png" /> PUERTO LOPEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_727.png" /> PUERTO MISAHUALLI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_728.png" /> PUERTO MURIALDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_729.png" /> PUERTO NAPO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_730.png" /> PUERTO PECHICHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_731.png" /> PUERTO QUITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_732.png" /> PUERTO RODRIGUEZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_733.png" /> PUERTO VILLAMIL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_734.png" /> PUJILI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_735.png" /> PUMALLACTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_736.png" /> PUMPUENTSA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_737.png" /> PUNA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_738.png" /> PUNGALA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_739.png" /> PUNIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_740.png" /> PURUNUMA /EGUIGUREN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_741.png" /> PUYO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_742.png" /> QUERO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_743.png" /> QUEVEDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_744.png" /> QUILANGA /LA PAZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_745.png" /> QUIMIAG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_746.png" /> QUINARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_747.png" /> QUINCHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_748.png" /> QUINCHICOTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_749.png" /> QUINGEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_750.png" /> QUINGUE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_751.png" /> QUINSALOMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_752.png" /> QUIROGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_753.png" /> QUISAPINCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_754.png" /> QUITUMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_755.png" /> RAMIREZ DAVALOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_756.png" /> RAMON CAMPAÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_757.png" /> REGULO DE MORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_758.png" /> REMIGIO CRESPO TORAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_759.png" /> RICAURTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_760.png" /> RIO BLANCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_761.png" /> RIO BONITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_762.png" /> RIO CHICO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_763.png" /> RIO CORRIENTES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_764.png" /> RIO NEGRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_765.png" /> RIO TIGRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_766.png" /> RIO TOACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_767.png" /> RIO VERDE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_768.png" /> RIVERA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_769.png" /> ROBERTO ASTUDILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_770.png" /> ROCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_771.png" /> ROCAFUERTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_772.png" /> ROSA FLORIDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_773.png" /> ROSA ZARATE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_774.png" /> ROSARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_775.png" /> RUMIPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_776.png" /> S. MIGUEL DE LOS BANCOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_777.png" /> SABANILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_778.png" /> SABIANGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_779.png" /> SACAPALCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_780.png" /> SAGRARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_781.png" /> SALANGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_782.png" /> SALASACA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_783.png" /> SALATI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_784.png" /> SALIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_785.png" /> SALINAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_786.png" /> SALITRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_787.png" /> SALVIAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_788.png" /> SAMBORONDON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_789.png" /> SAN ANDRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_790.png" /> SAN ANTONIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_791.png" /> SAN ANTONIO / DEL PELUDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_792.png" /> SAN ANTONIO DE BAYUSHIG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_793.png" /> SAN ANTONIO DE CUMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_794.png" /> SAN ANTONIO DE LAS ARADAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_795.png" /> SAN BARTOLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_796.png" /> SAN BARTOLOME<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_797.png" /> SAN BLAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_798.png" /> SAN BUENAVENTURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_799.png" /> SAN CAMILO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_800.png" /> SAN CARLOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_801.png" /> SAN CARLOS DE LAS MINAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_802.png" /> SAN CARLOS DE LIMON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_803.png" /> SAN CRISTOBAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_804.png" /> SAN FCO. DE CHINIMBIMI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_805.png" /> SAN FCO. DE SAGEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_806.png" /> SAN FCO.DE NATABUELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_807.png" /> SAN FERNANDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_808.png" /> SAN FRANCISCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_809.png" /> SAN FRANCISCO DE BORJA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_810.png" /> SAN FRANCISCO DE ONZOLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_811.png" /> SAN FRANCISCO DE SIGSIPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_812.png" /> SAN FRANCISCO DEL VERGEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_813.png" /> SAN GERARDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_814.png" /> SAN GERARDO / PAQUICAHUAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_815.png" /> SAN GREGORIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_816.png" /> SAN ISIDRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_817.png" /> SAN ISIDRO DE PATULU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_818.png" /> SAN ISIDRO DEL INCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_819.png" /> SAN JACINTO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_820.png" /> SAN JACINTO DE WAKAMBEIS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_821.png" /> SAN JACINTO DEL BUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_822.png" /> SAN JAVIER DE CACHABI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_823.png" /> SAN JOAQUIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_824.png" /> SAN JOSE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_825.png" /> SAN JOSE DE ANCON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_826.png" /> SAN JOSE DE AYORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_827.png" /> SAN JOSE DE CAYAPAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_828.png" /> SAN JOSE DE CHALTURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_829.png" /> SAN JOSE DE CHAMANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_830.png" /> SAN JOSE DE CHIMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_831.png" /> SAN JOSE DE DAHUANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_832.png" /> SAN JOSE DE GUAYUSA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_833.png" /> SAN JOSE DE MINAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_834.png" /> SAN JOSE DE MORONA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_835.png" /> SAN JOSE DE PAYAMINO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_836.png" /> SAN JOSE DE POALO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_837.png" /> SAN JOSE DE QUICHINCHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_838.png" /> SAN JOSE DE RARANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_839.png" /> SAN JOSE DE TAMBO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_840.png" /> SAN JOSE DEL CHAZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_841.png" /> SAN JUAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_842.png" /> SAN JUAN BOSCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_843.png" /> SAN JUAN DE CERRO AZUL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_844.png" /> SAN JUAN DE ILUMAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_845.png" /> SAN JUAN DE MUYUNA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_846.png" /> SAN JUAN DE PASTOCALLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_847.png" /> SAN JUAN DE POZUL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_848.png" /> SAN LORENZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_849.png" /> SAN LORENZO DE JIPIJAPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_850.png" /> SAN LUCAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_851.png" /> SAN LUIS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_852.png" /> SAN LUIS DE ARMENIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_853.png" /> SAN LUIS DE PAMBIL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_854.png" /> SAN LUIS DEL ACHO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_855.png" /> SAN MARTIN DE PUZHIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_856.png" /> SAN MATEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_857.png" /> SAN MIGUEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_858.png" /> SAN MIGUEL DE CONCHAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_859.png" /> SAN MIGUEL DE CUYES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_860.png" /> SAN MIGUEL DE SALCEDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_861.png" /> SAN MIGUELITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_862.png" /> SAN PABLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_863.png" /> SAN PABLO DE ATENAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_864.png" /> SAN PABLO DE TENTA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_865.png" /> SAN PABLO DE USHPAYACU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_866.png" /> SAN PEDRO DE LA BENDITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_867.png" /> SAN PEDRO DE LOS COFANES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_868.png" /> SAN PEDRO DE SUMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_869.png" /> SAN PEDRO DE TABOADA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_870.png" /> SAN PEDRO DE VILCABAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_871.png" /> SAN PLACIDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_872.png" /> SAN RAFAEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_873.png" /> SAN RAFAEL DE SHARUG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_874.png" /> SAN ROQUE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_875.png" /> SAN SALVADOR DE CAÑARIBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_876.png" /> SAN SEBASTIAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_877.png" /> SAN SEBASTIAN DE COCA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_878.png" /> SAN SEBASTIAN DE YULOG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_879.png" /> SAN SIMON<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_880.png" /> SAN VICENTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_881.png" /> SAN VICENTE DE HUATICOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_882.png" /> SAN VICENTE DE PUSIR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_883.png" /> SANGAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_884.png" /> SANGOLQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_885.png" /> SANGUILLIN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_886.png" /> SANTA ANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_887.png" /> SANTA BARBARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_888.png" /> SANTA CECILIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_889.png" /> SANTA CLARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_890.png" /> SANTA ELENA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_891.png" /> SANTA FE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_892.png" /> SANTA FE DE GALAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_893.png" /> SANTA ISABEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_894.png" /> SANTA LUCIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_895.png" /> SANTA LUCIA DE LAS PEÑAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_896.png" /> SANTA MARIA DEL TOACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_897.png" /> SANTA MARIANITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_898.png" /> SANTA MARIANITA DE JESUS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_899.png" /> SANTA MARTHA DE CUBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_900.png" /> SANTA RITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_901.png" /> SANTA ROSA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_902.png" /> SANTA ROSA DE FLANDES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_903.png" /> SANTA ROSA DE QUIJOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_904.png" /> SANTA ROSA DE SUCUMBIOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_905.png" /> SANTA RUFINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_906.png" /> SANTA SUSANA DE CHIVIAZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_907.png" /> SANTA TERESITA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_908.png" /> SANTIAGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_909.png" /> SANTIAGO DE PANANZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_910.png" /> SANTIAGO DE QUITO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_911.png" /> SANTO DOMINGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_912.png" /> SANTO DOMINGO DE ONZOLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_913.png" /> SAQUISILI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_914.png" /> SARACAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_915.png" /> SARAGURO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_916.png" /> SARDINAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_917.png" /> SAYAUSI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_918.png" /> SELVA ALEGRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_919.png" /> SEVILLA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_920.png" /> SEVILLA DE ORO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_921.png" /> SEVILLA DON BOSCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_922.png" /> SHAGLLI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_923.png" /> SHELL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_924.png" /> SHIMPIS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_925.png" /> SHUSHUFINDI CENTRAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_926.png" /> SIBAMBE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_927.png" /> SICALPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_928.png" /> SIDCAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_929.png" /> SIETE DE JULIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_930.png" /> SIETE DE OCTUBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_931.png" /> SIGCHOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_932.png" /> SIGSIG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_933.png" /> SIMIATUG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_934.png" /> SIMON BOLIVAR<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_935.png" /> SIMON PLATA TORRES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_936.png" /> SINAI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_937.png" /> SININCAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_938.png" /> SINSAO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_939.png" /> SN JACINTO DE BUENA FE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_940.png" /> SOLANDA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_941.png" /> SOLANO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_942.png" /> SOZORANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_943.png" /> STA. MARIA DE HUIRIRIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_944.png" /> STA.ROSA DE CUSUBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_945.png" /> SUA/BOCANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_946.png" /> SUCRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_947.png" /> SUCUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_948.png" /> SUMACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_949.png" /> SUMAYPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_950.png" /> SUSCAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_951.png" /> SUSUDEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_952.png" /> TABABELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_953.png" /> TABACUNDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_954.png" /> TABIAZO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_955.png" /> TACAMOROS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_956.png" /> TACHINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_957.png" /> TADAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_958.png" /> TAISHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_959.png" /> TALAG<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_960.png" /> TAMBILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_961.png" /> TANICUCHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_962.png" /> TAQUIL /MIGUEL RIOFRIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_963.png" /> TARACOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_964.png" /> TARAPOA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_965.png" /> TARIFA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_966.png" /> TARQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_967.png" /> TAURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_968.png" /> TAYUZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_969.png" /> TELEMBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_970.png" /> TELIMBELA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_971.png" /> TENA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_972.png" /> TENDALES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_973.png" /> TENGUEL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_974.png" /> TIMBARA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_975.png" /> TIMBIRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_976.png" /> TINGO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_977.png" /> TIPUTINI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_978.png" /> TISALEO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_979.png" /> TIXAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_980.png" /> TNTE M.RODRIGUEZ LOAYZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_981.png" /> TNTE. HUGO ORTIZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_982.png" /> TOACASO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_983.png" /> TOBAR DONOSO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_984.png" /> TOCACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_985.png" /> TOMAS DE BERLANGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_986.png" /> TOMEBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_987.png" /> TONCHIGUE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_988.png" /> TONSUPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_989.png" /> TORATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_990.png" /> TOSAGUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_991.png" /> TOTORACOCHA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_992.png" /> TOTORAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_993.png" /> TRES CERRITOS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_994.png" /> TRES DE NOVIEMBRE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_995.png" /> TRIUNFO DORADO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_996.png" /> TUFIÑO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_997.png" /> TULCAN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_998.png" /> TULULBI /RICAURTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_999.png" /> TUMBABIRO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1000.png" /> TUMBACO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1001.png" /> TUNDAYME<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1002.png" /> TUPIGACHI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1003.png" /> TURI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1004.png" /> TURUBAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1005.png" /> TURUPAMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1006.png" /> TUTINENTZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1007.png" /> TUTUPALI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1008.png" /> ULBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1009.png" /> UNAMUNCHO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1010.png" /> UNION LOJANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1011.png" /> UNION MILAGREÑA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1012.png" /> URBINA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1013.png" /> URCUQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1014.png" /> URDANETA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1015.png" /> URDANETA/PAQUISHAPA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1016.png" /> UTUANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1017.png" /> UYUMBICHO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1018.png" /> UZHCURRUMI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1019.png" /> VACAS GALINDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1020.png" /> VALDEZ/LIMONES/<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1021.png" /> VALENCIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1022.png" /> VALLADOLID<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1023.png" /> VALLE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1024.png" /> VALLE DE LA VIRGEN<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1025.png" /> VALLE HERMOSO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1026.png" /> VALPARAISO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1027.png" /> VELASCO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1028.png" /> VELASCO IBARRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1029.png" /> VELOZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1030.png" /> VENTANAS<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1031.png" /> VENTURA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1032.png" /> VENUS DEL RIO QUEVEDO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1033.png" /> VERACRUZ<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1034.png" /> VICENTE ROCAFUERTE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1035.png" /> VICENTINO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1036.png" /> VICHE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1037.png" /> VICTORIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1038.png" /> VICTORIA DEL PORTETE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1039.png" /> VILCABAMBA/VICTORIA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1040.png" /> VINCES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1041.png" /> VIRGEN DE FATIMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1042.png" /> VIVA ALFARO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1043.png" /> VUELTA LARGA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1044.png" /> WILFRIDO LOOR MOREIRA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1045.png" /> XIMENA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1046.png" /> YAGUACHI NUEVO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1047.png" /> YAGUACHI VIEJO/CONE<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1048.png" /> YAMANA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1049.png" /> YANAYACU MOCHAPATA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1050.png" /> YANGANA / ARSENIO CASTILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1051.png" /> YANUNCAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1052.png" /> YANZATZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1053.png" /> YARUQUI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1054.png" /> YARUQUIES<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1055.png" /> YASUNI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1056.png" /> YAUPI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1057.png" /> YUNGANZA /EL ROSARIO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1058.png" /> ZAMBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1059.png" /> ZAMBIZA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1060.png" /> ZAMORA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1061.png" /> ZAPALLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1062.png" /> ZAPOTAL<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1063.png" /> ZAPOTILLO<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1064.png" /> ZARACAY<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1065.png" /> ZARAYACU<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1066.png" /> ZARUMA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1067.png" /> ZHIDMAD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1068.png" /> ZHUD<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1069.png" /> ZUMBA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1070.png" /> ZUMBAHUA<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1071.png" /> ZUMBI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1072.png" /> ZUNAC<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1073.png" /> ZURMI<br />\
    <img src="styles/legend/LIMITE_PARROQUIAL_COD_CNE_1_1074.png" /> <br />'
        });
var lyr_Recorrido_manual_2 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "https://geoserver.idesinde.com:8443/geoserver/ows",
    attributions: ' ',
                              params: {
                                "LAYERS": "Lopez:Recorrido_manual",
                                "TILED": "true",
                                "VERSION": "1.3.0"},
                            })),
                            title: "Recorrido_manual",
                            opacity: 1.000000,
                            
                            
                          });
              wms_layers.push([lyr_Recorrido_manual_2, 1]);

lyr_quito2019style_0.setVisible(true);lyr_LIMITE_PARROQUIAL_COD_CNE_1.setVisible(true);lyr_Recorrido_manual_2.setVisible(true);
var layersList = [lyr_quito2019style_0,lyr_LIMITE_PARROQUIAL_COD_CNE_1,lyr_Recorrido_manual_2];
lyr_LIMITE_PARROQUIAL_COD_CNE_1.set('fieldAliases', {'CODPRO': 'CODPRO', 'PROVINCIA': 'PROVINCIA', 'CODCAN': 'CODCAN', 'CANTON': 'CANTON', 'CODPAR': 'CODPAR', 'PARROQUIA': 'PARROQUIA', 'ESTADO': 'ESTADO', 'Area': 'Area', 'PERIMETRO': 'PERIMETRO', 'Cent_X': 'Cent_X', 'cent_y': 'cent_y', });
lyr_LIMITE_PARROQUIAL_COD_CNE_1.set('fieldImages', {'CODPRO': 'TextEdit', 'PROVINCIA': 'TextEdit', 'CODCAN': 'TextEdit', 'CANTON': 'TextEdit', 'CODPAR': 'TextEdit', 'PARROQUIA': 'TextEdit', 'ESTADO': 'TextEdit', 'Area': 'TextEdit', 'PERIMETRO': 'TextEdit', 'Cent_X': 'TextEdit', 'cent_y': 'TextEdit', });
lyr_LIMITE_PARROQUIAL_COD_CNE_1.set('fieldLabels', {'CODPRO': 'no label', 'PROVINCIA': 'no label', 'CODCAN': 'no label', 'CANTON': 'no label', 'CODPAR': 'no label', 'PARROQUIA': 'no label', 'ESTADO': 'no label', 'Area': 'inline label - always visible', 'PERIMETRO': 'no label', 'Cent_X': 'no label', 'cent_y': 'no label', });
lyr_LIMITE_PARROQUIAL_COD_CNE_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});